kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: persistent-volume-claim-nas
  annotations:
     trident.netapp.io/snapshotPolicy: "default"
     trident.netapp.io/snapshotDirectory: "true"
     trident.netapp.io/reclaimPolicy: "Retain"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: storage-class-nas
  resources:
    requests:
      storage: 1Gi
